# Generated by Django 4.1.7 on 2023-04-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
